export const upcomingTrainsResponse = [
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E923 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Greystones'],
    Destination: ['Howth'],
    Origintime: ['13:04'],
    Destinationtime: ['14:28'],
    Status: ['En Route'],
    Lastlocation: ['Departed Sutton'],
    Duein: ['5'],
    Late: ['0'],
    Exparrival: ['14:28'],
    Expdepart: ['00:00'],
    Scharrival: ['14:28'],
    Schdepart: ['00:00'],
    Direction: ['Northbound'],
    Traintype: ['DART'],
    Locationtype: ['D'],
  },
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E924 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Bray'],
    Destination: ['Howth'],
    Origintime: ['13:35'],
    Destinationtime: ['14:49'],
    Status: ['En Route'],
    Lastlocation: ['Arrived Dublin Connolly'],
    Duein: ['26'],
    Late: ['0'],
    Exparrival: ['14:49'],
    Expdepart: ['00:00'],
    Scharrival: ['14:49'],
    Schdepart: ['00:00'],
    Direction: ['Northbound'],
    Traintype: ['DART'],
    Locationtype: ['D'],
  },
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E925 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Bray'],
    Destination: ['Howth'],
    Origintime: ['13:55'],
    Destinationtime: ['15:08'],
    Status: ['En Route'],
    Lastlocation: ['Departed Blackrock'],
    Duein: ['46'],
    Late: ['1'],
    Exparrival: ['15:09'],
    Expdepart: ['00:00'],
    Scharrival: ['15:08'],
    Schdepart: ['00:00'],
    Direction: ['Northbound'],
    Traintype: ['DART'],
    Locationtype: ['D'],
  },
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E926 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Greystones'],
    Destination: ['Howth'],
    Origintime: ['14:04'],
    Destinationtime: ['15:29'],
    Status: ['En Route'],
    Lastlocation: ['Arrived Killiney'],
    Duein: ['65'],
    Late: ['-1'],
    Exparrival: ['15:28'],
    Expdepart: ['00:00'],
    Scharrival: ['15:29'],
    Schdepart: ['00:00'],
    Direction: ['Northbound'],
    Traintype: ['DART'],
    Locationtype: ['D'],
  },
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E927 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Bray'],
    Destination: ['Howth'],
    Origintime: ['14:35'],
    Destinationtime: ['15:51'],
    Status: ['No Information'],
    Lastlocation: [''],
    Duein: ['88'],
    Late: ['0'],
    Exparrival: ['15:51'],
    Expdepart: ['00:00'],
    Scharrival: ['15:51'],
    Schdepart: ['00:00'],
    Direction: ['Northbound'],
    Traintype: ['DART'],
    Locationtype: ['D'],
  },
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E236 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Howth'],
    Destination: ['Bray'],
    Origintime: ['14:43'],
    Destinationtime: ['15:57'],
    Status: ['No Information'],
    Lastlocation: [''],
    Duein: ['20'],
    Late: ['0'],
    Exparrival: ['00:00'],
    Expdepart: ['14:43'],
    Scharrival: ['00:00'],
    Schdepart: ['14:43'],
    Direction: ['Southbound'],
    Traintype: ['DART'],
    Locationtype: ['O'],
  },
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E119 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Howth'],
    Destination: ['Greystones'],
    Origintime: ['15:00'],
    Destinationtime: ['16:26'],
    Status: ['No Information'],
    Lastlocation: [''],
    Duein: ['37'],
    Late: ['0'],
    Exparrival: ['00:00'],
    Expdepart: ['15:00'],
    Scharrival: ['00:00'],
    Schdepart: ['15:00'],
    Direction: ['Southbound'],
    Traintype: ['DART'],
    Locationtype: ['O'],
  },
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E239 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Howth'],
    Destination: ['Bray'],
    Origintime: ['15:20'],
    Destinationtime: ['16:35'],
    Status: ['No Information'],
    Lastlocation: [''],
    Duein: ['57'],
    Late: ['0'],
    Exparrival: ['00:00'],
    Expdepart: ['15:20'],
    Scharrival: ['00:00'],
    Schdepart: ['15:20'],
    Direction: ['Southbound'],
    Traintype: ['DART'],
    Locationtype: ['O'],
  },
  {
    Servertime: ['2020-07-23T14:23:53.327'],
    Traincode: ['E240 '],
    Stationfullname: ['Howth'],
    Stationcode: ['HOWTH'],
    Querytime: ['14:23:53'],
    Traindate: ['23 Jul 2020'],
    Origin: ['Howth'],
    Destination: ['Bray'],
    Origintime: ['15:40'],
    Destinationtime: ['16:55'],
    Status: ['No Information'],
    Lastlocation: [''],
    Duein: ['77'],
    Late: ['0'],
    Exparrival: ['00:00'],
    Expdepart: ['15:40'],
    Scharrival: ['00:00'],
    Schdepart: ['15:40'],
    Direction: ['Southbound'],
    Traintype: ['DART'],
    Locationtype: ['O'],
  },
];
