export const MESSAGE_TYPES = {
  bot: 'bot',
  user: 'user',
};

export const STATION_LIST = [
  'Malahide',
  'Portmarnock',
  'Clongriffin',
  'Sutton',
  'Bayside',
  'Howth Junction',
  'Howth',
  'Kilbarrack',
  'Raheny',
  'Harmonstown',
  'Killester',
  'Clontarf Road',
  'Dublin Connolly',
  'Tara Street',
  'Dublin Pearse',
  'Grand Canal Dock',
  'Lansdowne Road',
  'Sandymount',
  'Sydney Parade',
  'Booterstown',
  'Blackrock',
  'Seapoint',
  'Salthill and Monkstown',
  'Dun Laoghaire',
  'Sandycove',
  'Glenageary',
  'Dalkey',
  'Killiney',
  'Shankill',
  'Bray',
  'Greystones',
  'Kilcoole',
];
